export const ALGERIA_WILAYAS = [
  { code: 1, name: 'Adrar', communes: ['Adrar', 'Reggane', 'Aoulef', 'Timimoun'] },
  { code: 2, name: 'Chlef', communes: ['Chlef', 'Ténès', 'El Abadia'] },
  { code: 3, name: 'Laghouat', communes: ['Laghouat', 'Aflou', 'Ksar El Hirane'] },
  { code: 4, name: 'Oum El Bouaghi', communes: ['Oum El Bouaghi', 'Aïn Beïda', 'Ain Fakroun'] },
  { code: 5, name: 'Batna', communes: ['Batna', 'Barika', 'Arris', 'Merouana'] },
  { code: 6, name: 'Béjaïa', communes: ['Béjaïa', 'Akbou', 'Aokas', 'Kherrata'] },
  { code: 7, name: 'Biskra', communes: ['Biskra', 'Tolga', 'Ourlal', 'Sidi Okba'] },
  { code: 8, name: 'Béchar', communes: ['Béchar', 'Abadla', 'Beni Abbes'] },
  { code: 9, name: 'Blida', communes: ['Blida', 'Boufarik', 'Larbaa', 'Meftah', 'Chréa'] },
  { code: 10, name: 'Bouira', communes: ['Bouira', 'Lakhdaria', 'Sour El-Ghozlane'] },
  { code: 11, name: 'Tamanrasset', communes: ['Tamanrasset', 'In Salah', 'In Guezzam'] },
  { code: 12, name: 'Tébessa', communes: ['Tébessa', 'Bir El-Ater', 'Cheria'] },
  { code: 13, name: 'Tlemcen', communes: ['Tlemcen', 'Maghnia', 'Ghazaouet', 'Nedroma'] },
  { code: 14, name: 'Tiaret', communes: ['Tiaret', 'Sougueur', 'Ksar Chellala'] },
  { code: 15, name: 'Tizi Ouzou', communes: ['Tizi Ouzou', 'Azazga', 'Draa Ben Khedda', 'Boghni'] },
  { code: 16, name: 'Alger', communes: ['Alger Centre', 'Bab El Oued', 'Cheraga', 'Draria', 'Bir Mourad Raïs', 'El Harrach', 'Rouiba', 'Reghaia', 'Birkhadem', 'Bouzareah', 'Hussein Dey', 'Kouba', 'El Biar'] },
  { code: 17, name: 'Djelfa', communes: ['Djelfa', 'Messaad', 'Ain Oussera', 'Birine'] },
  { code: 18, name: 'Jijel', communes: ['Jijel', 'Taher', 'El Milia', 'Ziama Mansouriah'] },
  { code: 19, name: 'Sétif', communes: ['Sétif', 'El Eulma', 'Bougaa', 'Ain Azel'] },
  { code: 20, name: 'Saïda', communes: ['Saïda', 'Aïn El Hadjar', 'Youb'] },
  { code: 21, name: 'Skikda', communes: ['Skikda', 'Azzaba', 'Collo', 'El Harrouch'] },
  { code: 22, name: 'Sidi Bel Abbès', communes: ['Sidi Bel Abbès', 'Telagh', 'Sfisef', 'Ras El Ma'] },
  { code: 23, name: 'Annaba', communes: ['Annaba', 'El Bouni', 'Berrahal', 'El Hadjar'] },
  { code: 24, name: 'Guelma', communes: ['Guelma', 'Bouchegouf', 'Heliopolis'] },
  { code: 25, name: 'Constantine', communes: ['Constantine', 'El Khroub', 'Hamma Bouziane', 'Ain Smara'] },
  { code: 26, name: 'Médéa', communes: ['Médéa', 'Berrouaghia', 'Ksar El Boukhari', 'Tablat'] },
  { code: 27, name: 'Mostaganem', communes: ['Mostaganem', 'Relizane', 'Ain Tedeles'] },
  { code: 28, name: 'MSila', communes: ['MSila', 'Bou Saada', 'Ain El Melh', 'Magra'] },
  { code: 29, name: 'Mascara', communes: ['Mascara', 'Mohammadia', 'Tighennif', 'Ain Fares'] },
  { code: 30, name: 'Ouargla', communes: ['Ouargla', 'Hassi Messaoud', 'Touggourt', 'Ain Beida'] },
  { code: 31, name: 'Oran', communes: ['Oran', 'Es Sénia', 'Bir El Djir', 'Arzew', 'Ain Turk'] },
  { code: 32, name: 'El Bayadh', communes: ['El Bayadh', 'Brezina', 'Chellala'] },
  { code: 33, name: 'Illizi', communes: ['Illizi', 'Djanet', 'In Amenas'] },
  { code: 34, name: 'Bordj Bou Arréridj', communes: ['Bordj Bou Arreridj', 'Ras El Oued', 'Bordj Ghedir'] },
  { code: 35, name: 'Boumerdès', communes: ['Boumerdès', 'Dellys', 'Khemis El Khechna', 'Boudouaou'] },
  { code: 36, name: 'El Tarf', communes: ['El Tarf', 'Ben Mehidi', 'Chihani'] },
  { code: 37, name: 'Tindouf', communes: ['Tindouf', 'Oum El Assel'] },
  { code: 38, name: 'Tissemsilt', communes: ['Tissemsilt', 'Theniet El Had', 'Khemisti'] },
  { code: 39, name: 'El Oued', communes: ['El Oued', 'Debila', 'Robbah', 'Guemar'] },
  { code: 40, name: 'Khenchela', communes: ['Khenchela', 'Ain Touila', 'Babar'] },
  { code: 41, name: 'Souk Ahras', communes: ['Souk Ahras', 'Sedrata', 'Merahna'] },
  { code: 42, name: 'Tipaza', communes: ['Tipaza', 'Hadjout', 'Bourkika', 'Cherchell', 'Kolea'] },
  { code: 43, name: 'Mila', communes: ['Mila', 'Ferdjioua', 'Chelghoum Laïd', 'Ain Beida Harriche'] },
  { code: 44, name: 'Aïn Defla', communes: ['Ain Defla', 'Khemis Miliana', 'El Attaf', 'Ain Lechiakh'] },
  { code: 45, name: 'Naâma', communes: ['Naama', 'Mechria', 'Ain Sefra', 'Tiout'] },
  { code: 46, name: 'Aïn Témouchent', communes: ['Ain Temouchent', 'Hammam Bou Hadjar', 'El Amria'] },
  { code: 47, name: 'Ghardaïa', communes: ['Ghardaia', 'Bounoura', 'El Menia', 'Berriane'] },
  { code: 48, name: 'Relizane', communes: ['Relizane', 'Mazouna', 'Oued Rhiou', 'Ain Tarek'] },
  { code: 49, name: 'Timimoun', communes: ['Timimoun', 'Charouine', 'Aougrout'] },
  { code: 50, name: 'Bordj Badji Mokhtar', communes: ['Bordj Badji Mokhtar', 'Timiaouine'] },
  { code: 51, name: 'Ouled Djellal', communes: ['Ouled Djellal', 'Ras El Miad', 'Sidi Khaled'] },
  { code: 52, name: 'Béni Abbès', communes: ['Beni Abbes', 'Igli', 'El Ouata'] },
  { code: 53, name: 'In Salah', communes: ['In Salah', 'In Ghar', 'Foggaret Ezzaouia'] },
  { code: 54, name: 'In Guezzam', communes: ['In Guezzam', 'Tin Zaouatine'] },
  { code: 55, name: 'Touggourt', communes: ['Touggourt', 'Temacine', 'Megarine', 'Nezla'] },
  { code: 56, name: 'Djanet', communes: ['Djanet', 'Bordj El Haouès'] },
  { code: 57, name: 'El MGhair', communes: ['El Mghaier', 'Djamaa', 'Still', 'Sidi Amrane'] },
  { code: 58, name: 'El Meniaa', communes: ['El Menia', 'Hassi Gara'] },
];

export type AlgeriaWilaya = typeof ALGERIA_WILAYAS[0];
